# Generated by Django 3.2.23 on 2023-11-26 08:18

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffDayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('SOD', models.CharField(max_length=10, verbose_name='شماره درخواست')),
                ('StartDate', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('EndDate', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('Status', models.CharField(choices=[('1', 'جدید'), ('2', 'در حال بررسی'), ('3', 'رد شده'), ('4', 'تایید شده')], default='1', max_length=50, verbose_name='وضعیت')),
                ('Type', models.CharField(choices=[('1', 'استحقاقی'), ('2', 'بدون حقوق')], default='1', max_length=50, verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'OffDayRequest',
                'verbose_name_plural': 'OffDayRequests',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('SRE', models.CharField(max_length=10, unique=True, verbose_name='کد پرسنلی')),
                ('FirstName', models.CharField(max_length=50, verbose_name='نام')),
                ('LastName', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('Phone', models.CharField(max_length=13, verbose_name='شماره همراه')),
                ('NationalID', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('Email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('JobTitle', models.CharField(max_length=100, verbose_name='عنوان شغلی')),
                ('Status', models.CharField(choices=[('1', 'جدید'), ('2', 'مشغول به کار'), ('3', 'تعلیق'), ('4', 'اخراج'), ('5', 'ترک مجموعه'), ('6', 'مرخصی')], default='1', max_length=20, verbose_name='وضعیت')),
                ('Mood', models.CharField(choices=[('1', 'خیلی خوشحال'), ('2', 'خوشحال'), ('3', 'معمولی'), ('4', 'بی تفاوت'), ('5', 'بی حوصله'), ('6', 'مزاحمم نشید'), ('7', 'عصبانی'), ('8', 'افسرده')], default='4', max_length=20, verbose_name='مود رفتاری')),
                ('Joined', models.DateField(verbose_name='تاریخ شروع همکاری')),
                ('Left', models.DateField(verbose_name='تاریخ پایان همکاری')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personels',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('ST', models.CharField(max_length=10, verbose_name='کد تیم')),
                ('Name', models.CharField(max_length=50, verbose_name='نام تیم')),
                ('Description', models.TextField(max_length=600, verbose_name='توضیحات')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('Parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Admins.team')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
    ]
