# Generated by Django 3.2.23 on 2023-11-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admins', '0001_initial'),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.address', verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='personel',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admins.team', verbose_name='تیم'),
        ),
        migrations.AddField(
            model_name='offdayrequest',
            name='Personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.personel', verbose_name='پرسنل'),
        ),
    ]
