# Generated by Django 3.2.23 on 2023-11-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0003_auto_20231127_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Parent',
            new_name='parent',
        ),
    ]
