# Generated by Django 3.2.23 on 2023-11-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0005_auto_20231127_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personel',
            old_name='SRE',
            new_name='SPE',
        ),
    ]
