# Generated by Django 3.2.23 on 2023-11-28 08:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admins', '0006_rename_sre_personel_spe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personel',
            options={'verbose_name': 'Personel', 'verbose_name_plural': 'Personels'},
        ),
        migrations.AlterModelManagers(
            name='personel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='personel',
            name='Created',
        ),
        migrations.RemoveField(
            model_name='personel',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='personel',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='personel',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='personel',
            name='Modified',
        ),
        migrations.RemoveField(
            model_name='personel',
            name='id',
        ),
        migrations.AddField(
            model_name='personel',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
