# Generated by Django 3.2.23 on 2023-11-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Admins', '0008_auto_20231130_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='دسترسی'),
        ),
    ]
