# Generated by Django 3.2.23 on 2023-12-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0009_team_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='offdayrequest',
            name='Active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='team',
            name='Active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
