# Generated by Django 3.2.23 on 2023-12-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0010_auto_20231213_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offdayrequest',
            name='Personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offreq_personel', to='Admins.personel', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='Joined',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ شروع همکاری'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pers_team', to='Admins.team', verbose_name='تیم'),
        ),
    ]
