# Generated by Django 3.2.23 on 2023-12-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0011_auto_20231225_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='BirthDate',
            field=models.CharField(default=0, max_length=50, verbose_name='تاریخ تولد'),
            preserve_default=False,
        ),
    ]
