# Generated by Django 3.2.23 on 2024-01-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0012_personel_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='Picture',
            field=models.ImageField(default=0, height_field=500, max_length=500, upload_to='Admins/', verbose_name='تصویر پروفایل', width_field=500),
            preserve_default=False,
        ),
    ]
