# Generated by Django 3.2.23 on 2024-01-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0013_personel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='Picture',
            field=models.ImageField(height_field='500', max_length='500', upload_to='Admins/', verbose_name='تصویر پروفایل', width_field='500'),
        ),
    ]
