# Generated by Django 3.2.23 on 2024-01-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0017_alter_personel_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('Active', models.BooleanField(default=True, verbose_name='فعال')),
                ('Title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('Institude', models.CharField(max_length=200, verbose_name='موسسه/دانشگاه')),
                ('StartDate', models.CharField(max_length=50, verbose_name='تاریخ شروع')),
                ('EndDate', models.CharField(max_length=50, verbose_name='تاریخ پایان')),
                ('Personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_personel', to='Admins.personel', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': 'educations',
            },
        ),
    ]
