# Generated by Django 3.2.23 on 2023-11-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(max_length=100, verbose_name='عنوان آدرس')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('Phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('PostalAddress', models.CharField(max_length=500, verbose_name='آدرس پستی')),
                ('PostalCode', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('Number', models.CharField(max_length=4, verbose_name='پلاک')),
                ('Unit', models.CharField(blank=True, max_length=5, verbose_name='واحد')),
                ('Active', models.BooleanField(default=True, verbose_name='فعال')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_city', to='Main.city', verbose_name='شهر')),
                ('Personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.personel', verbose_name='پرسنل')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_city', to='Main.city', verbose_name='استان')),
            ],
            options={
                'verbose_name_plural': 'آدرس',
            },
        ),
    ]
