# Generated by Django 3.2.23 on 2023-11-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0002_initial'),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questonnair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('SQ', models.CharField(max_length=10, verbose_name='')),
                ('Form', models.TextField(verbose_name='')),
                ('DefaultForm', models.TextField(verbose_name='')),
                ('DeadLine', models.DateTimeField(blank=True, null=True, verbose_name='ددلاین')),
                ('Type', models.CharField(choices=[('1', 'نظرسنجی'), ('2', 'پرسشنامه')], default='1', max_length=50, verbose_name='نوع')),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.personel', verbose_name='')),
                ('Team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admins.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'Questonnair',
                'verbose_name_plural': 'Questonnairs',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('SQR', models.CharField(max_length=10, verbose_name='')),
                ('Form', models.TextField(verbose_name='')),
                ('Personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.personel', verbose_name='')),
                ('Questonnair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.questonnair', verbose_name='')),
            ],
            options={
                'verbose_name': 'Respondent',
                'verbose_name_plural': 'Respondents',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
    ]
