# Generated by Django 3.2.23 on 2023-11-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20231127_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questonnair',
            name='SQ',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='شماره پرسشنامه'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='SQR',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='شماره پاسخ'),
        ),
    ]
