# Generated by Django 3.2.23 on 2023-12-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0012_personel_birthdate'),
        ('Main', '0009_codereg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_pers', to='Admins.personel', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='Personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respond_pers', to='Admins.personel', verbose_name='کارمند'),
        ),
    ]
