# Generated by Django 3.2.23 on 2023-11-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0003_auto_20231127_0821'),
        ('Messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('SCM', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='شماره پیام')),
                ('Text', models.TextField(verbose_name='پیام')),
                ('Seen', models.BooleanField(default=False, verbose_name='دیده شده')),
                ('Name', models.CharField(max_length=50, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'ChatMessage',
                'verbose_name_plural': 'ChatMessages',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('Personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.personel', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'chatParticipant',
                'verbose_name_plural': 'chatParticipants',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='chatthread',
            options={'ordering': ['Created'], 'verbose_name': 'ChatThread', 'verbose_name_plural': 'ChatThreads'},
        ),
        migrations.AddField(
            model_name='chatthread',
            name='SCT',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد چت'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admins.team', verbose_name='تیم'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='Type',
            field=models.CharField(choices=[('1', 'شخصی'), ('2', 'گروهی')], default='1', max_length=50, verbose_name='نوع'),
        ),
        migrations.CreateModel(
            name='ThreadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('Action', models.CharField(max_length=100, verbose_name='اکشن')),
                ('Participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messaging.chatparticipant', verbose_name='عضو')),
                ('Thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messaging.chatthread', verbose_name='چت')),
            ],
            options={
                'verbose_name': 'ThreadLog',
                'verbose_name_plural': 'ThreadLogs',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('Action', models.CharField(max_length=100, verbose_name='اکشن')),
                ('Message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messaging.chatmessage', verbose_name='پیام')),
                ('Participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messaging.chatparticipant', verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'MessageLog',
                'verbose_name_plural': 'MessageLogs',
            },
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='Thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messaging.chatthread', verbose_name='چت'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='Participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messaging.chatparticipant', verbose_name='عضو'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='Thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messaging.chatthread', verbose_name='چت'),
        ),
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('File', models.FileField(upload_to='Chats/', verbose_name='فایل')),
                ('Message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messaging.chatmessage', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'ChatFile',
                'verbose_name_plural': 'ChatFiles',
            },
        ),
    ]
