# Generated by Django 3.2.23 on 2023-11-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0002_auto_20231127_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='SCM',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره پیام'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='SCT',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='کد چت'),
        ),
    ]
