# Generated by Django 3.2.23 on 2023-11-26 09:02

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admins', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('DeadLine', models.DateTimeField(blank=True, null=True, verbose_name='ددلاین')),
                ('Fulfilld', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات')),
                ('Report', models.TextField(blank=True, max_length=500, null=True, verbose_name='گزارش')),
                ('Status', models.CharField(choices=[('1', 'جدید'), ('2', 'در حال اجرا'), ('3', 'در انتظار تایید'), ('4', 'تایید شده'), ('5', 'رد شده'), ('6', 'لغو شده')], default='1', max_length=20, verbose_name='وضعیت')),
                ('SST', models.CharField(max_length=10, verbose_name='شماره ساب تسک')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('Parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Tasks.subtask')),
            ],
            options={
                'verbose_name': 'SubTask',
                'verbose_name_plural': 'SubTasks',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('DeadLine', models.DateTimeField(blank=True, null=True, verbose_name='ددلاین')),
                ('Fulfilld', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات')),
                ('Report', models.TextField(blank=True, max_length=500, null=True, verbose_name='گزارش')),
                ('Status', models.CharField(choices=[('1', 'جدید'), ('2', 'در حال اجرا'), ('3', 'در انتظار تایید'), ('4', 'تایید شده'), ('5', 'رد شده'), ('6', 'لغو شده')], default='1', max_length=20, verbose_name='وضعیت')),
                ('STA', models.CharField(max_length=10, verbose_name='شماره تسک')),
                ('Assigned_To', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_pers', to='Admins.personel', verbose_name='محول شده')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_pers', to='Admins.personel', verbose_name='کارفرما')),
                ('Team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admins.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STF', models.CharField(max_length=10, verbose_name='شماره فایل')),
                ('File', models.FileField(max_length=150, upload_to='Tasks/', verbose_name='فایل')),
                ('Type', models.CharField(choices=[('1', 'تسک'), ('2', 'جزئیات')], default='1', max_length=50, verbose_name='نوع')),
                ('Sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.subtask', verbose_name='ساب تسک')),
                ('Task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.task', verbose_name='تسک')),
            ],
            options={
                'verbose_name': 'TaskFile',
                'verbose_name_plural': 'TaskFiles',
            },
        ),
        migrations.AddField(
            model_name='subtask',
            name='Task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.task', verbose_name='تسک'),
        ),
    ]
