# Generated by Django 3.2.23 on 2023-11-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='SST',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='شماره ساب تسک'),
        ),
        migrations.AlterField(
            model_name='task',
            name='STA',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='شماره تسک'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='STF',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='شماره فایل'),
        ),
    ]
