# Generated by Django 3.2.23 on 2023-12-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_rename_parent_subtask_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='Active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='task',
            name='Active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
