# Generated by Django 3.2.23 on 2023-12-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0011_auto_20231225_0823'),
        ('Tasks', '0005_auto_20231213_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_team', to='Admins.team', verbose_name='تیم'),
        ),
    ]
