# Generated by Django 3.2.23 on 2023-11-28 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admins', '0006_rename_sre_personel_spe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('STK', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='کد تیکت')),
                ('User', models.IntegerField(default=0, verbose_name='خریدار')),
                ('Provider', models.IntegerField(default=0, verbose_name='فروشنده')),
                ('Subject', models.CharField(max_length=300, verbose_name='موضوع')),
                ('Type', models.CharField(choices=[('1', 'خریدار'), ('2', 'فروشنده')], default='1', max_length=50, verbose_name='کاربر هدف')),
                ('Status', models.CharField(choices=[('1', 'تیکت ادمین'), ('2', 'تیکت کاربر'), ('3', 'درحال بررسی'), ('4', 'پاسخ داده شده'), ('5', 'دیده شده'), ('6', 'باز'), ('7', 'بسته')], default='2', max_length=50, verbose_name='وضعیت')),
                ('Personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admins.personel', verbose_name='پرسنل')),
                ('Team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admins.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('STS', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره  سوییچ')),
                ('Type', models.CharField(choices=[('1', 'تیم'), ('2', 'هردو'), ('3', 'ادمین')], default='3', max_length=50, verbose_name='کاربر هدف')),
                ('NewPersonel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='np_switch_team', to='Admins.personel', verbose_name='پرسنل جدید')),
                ('NewTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nt_switch_team', to='Admins.team', verbose_name='تیم جدید')),
                ('OldPersonel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op_switch_team', to='Admins.personel', verbose_name='پرسنل قدیم')),
                ('OldTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ot_switch_team', to='Admins.team', verbose_name='تیم قدیم')),
                ('Ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'TicketSwitch',
                'verbose_name_plural': 'TicketSwitchs',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('STM', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره پیام')),
                ('Sender', models.CharField(choices=[('1', 'خریدار'), ('2', 'فروشنده'), ('3', 'ادمین')], default='1', max_length=50, verbose_name='فرستنده')),
                ('Text', models.TextField(verbose_name='پیام')),
                ('Name', models.CharField(max_length=50, verbose_name='نام')),
                ('Ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'TicketMessage',
                'verbose_name_plural': 'TicketMessages',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('File', models.FileField(upload_to='Tickets/', verbose_name='فایل')),
                ('Message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticketmessage', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'TicketFile',
                'verbose_name_plural': 'TicketFiles',
                'ordering': ['Created'],
                'abstract': False,
            },
        ),
    ]
